### ISSUE TITLE
Suggestions to improve CSS code formatting. 

### ISSUE THREAD

**Issue by josephtkim** [Codobots/prj-rev-bwfs-dasmoto#4]
As suggested in issue #3, it is always good to stay consistent with code formatting, to make the code easier to read and work with for other developers as well. Here is how you might format your CSS code to be more consistent, 

```css
h1 {
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
  color: Khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg")
}

#brushes {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: mediumspringgreen;
}

#frameheader {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: lightcoral;
}

#clean {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
  background-color: skyblue;
}

.price{
  font-family: Helvetica;
  font-weight: bold;
  color: blue;
}
```
