### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [Codobots/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are a few properties which are shared by several selectors. You can simplify the code like so,

```css
h1 {
  color: Khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg")
}

h1, h2, h3, .price {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}

#frameheader {
  background-color: lightcoral;
}

#clean {
  background-color: skyblue;
}

.price {
  color: blue;
}
```
